apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Proodle0911/next-gen-idp.git'
    targetRevision: main
    path: infrastructure/crossplane-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
