apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Next-Gen IDP
      baseUrl: http://localhost:7000
    backend:
      baseUrl: http://localhost:7000
      listen:
        port: 7000
      database:
        client: sqlite3
        connection: ':memory:'
        useNullAsDefault: true
      cors:
        origin: http://localhost:7000
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    rollbar:
      accessToken: 'dummy-token'
      accountToken: 'dummy-account-token'
      organization: 'dummy-org'
      project: 'dummy-project'
    auth:
      providers:
        guest: {}
    scaffolder:
      # Optional: custom configuration
    kubernetes:
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: local-cluster
              url: https://kubernetes.default.svc
              authProvider: serviceAccount
              serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
              skipTLSVerify: true
      serviceLocatorMethod:
        type: multiTenant
    catalog:
      locations:
        - type: url
          target: https://github.com/Proodle0911/next-gen-idp/blob/main/apps/template-go/template.yaml
          rules:
            - allow: [Template]
